stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    - data/external/pima-indians-diabetes.csv
    params:
    - make_dataset.test_size
    - make_dataset.random_state
    - make_dataset.column_names
    outs:
    - data/interim/train_data.csv
    - data/interim/test_data.csv

  data_preprocessing:
    cmd: python src/data/process_dataset.py
    deps:
    - src/data/process_dataset.py
    - data/interim/train_data.csv
    params:
    - process_dataset.column_name

  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
    - src/features/build_features.py
    - data/interim/train_data.csv
    - data/interim/test_data.csv
    outs:
    - data/processed/train_df_processed.csv
    - data/processed/test_df_processed.csv

  model_building:
    cmd: python src/models/train_model.py
    deps:
    - src/models/train_model.py
    - data/processed/train_df_processed.csv
    params:
    - train_model.n_estimators
    - train_model.max_features
    - train_model.max_depth
    - train_model.max_samples
    - train_model.verbose
    - train_model.random_state
    - train_model.n_jobs
    - train_model.min_samples_split
    - train_model.min_samples_leaf
    outs:
    - models/rfclf_model.joblib

  model_evaluation:
    cmd: python src/models/predict_model.py
    deps:
    - src/models/predict_model.py
    - data/processed/test_df_processed.csv    
    - models/rfclf_model.joblib
    metrics:
    - reports/metrics.json

    