make_dataset:
  data_source_url: https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv
  test_size: 0.3
  random_state: 42
  column_names:
  - Pregnancies
  - Glucose
  - BloodPressure
  - SkinThickness
  - Insulin
  - BMI
  - DiabetesPedigreeFunction
  - Age
  - Outcome

process_dataset:
  column_name:
  - Insulin

train_model:
  n_estimators:
  - 20
  - 60
  - 100
  - 120
  max_features:
  - 0.2
  - 0.6
  - 1.0
  max_depth:
  - 2
  - 8
  # - None
  max_samples:
  - 0.5
  - 0.75
  - 1.0
  min_samples_split:
  - 2
  - 5
  min_samples_leaf:
  - 1
  - 2
  verbose: 2
  random_state: 42
  n_jobs: -1
