name: MLOps project CI/CD Pipeline

on:
  push:
    branches: [ main ]          # test multiple branches [ main, feature-ci-run ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
      force_build:
        description: 'Force build even without code changes'
        required: false
        type: boolean
        default: false

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  IMAGE_NAME: 'mlops-project-patients-diabetes-prediction'
  PYTHON_VERSION: '3.12'
  CACHE_KEY: ${{ github.sha }}
  DVC_REMOTE_NAME: origin
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  run-pipeline-and-test:
    name: Install dependencies, run pipeline and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 mypy

      - name: Ingest the data and run ML pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python3 src/data/make_dataset.py
          dvc repro

      - name: Push the data to DVC remote
        env:
          DVC_ACCESS_KEY: ${{ secrets.DVC_ACCESS_KEY }}
        run: |
          dvc remote modify origin --local access_key_id "$DVC_ACCESS_KEY"
          dvc remote modify origin --local secret_access_key "$DVC_ACCESS_KEY"
          dvc commit || echo "No changes to commit"
          dvc push || { echo "DVC push failed"; exit 1; }

      # - name: Lint with flake8
      #   run: |
      #     flake8 src tests

      # - name: Type checking with mypy
      #   run: |
      #     mypy src

      - name: Test with pytest
        run: |
          pytest -vs --cov=src --cov-report=xml:coverage.xml tests/
        env:
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: warn  # This is actually the default, but making it explicit

  # security-scan:
  #   name: Security Scan
  #   runs-on: ubuntu-latest
  #   needs: run-pipeline-and-test
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}

  #     - name: Install security tools
  #       run: |
  #         pip install bandit safety

  #     - name: Run Bandit security scan
  #       run: |
  #         bandit -r src/ -f json -o bandit-results.json

  #     - name: Check for dependency vulnerabilities
  #       run: |
  #         safety check -r requirements.txt

  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         scan-type: 'fs'
  #         format: 'table'
  #         output: 'trivy-results.txt'
  #         severity: 'CRITICAL,HIGH'

  #     - name: Upload security scan results
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: security-scan-results
  #         path: |
  #           bandit-results.json
  #           trivy-results.txt

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [run-pipeline-and-test]          # TODO later: security-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for app code changes
        id: check_changes
        run: |
          echo "has_changes=false" >> $GITHUB_OUTPUT

          if [[ "${{ github.event.inputs.force_build }}" == "true" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Force build was enabled by user, proceeding with Docker build.."
          elif [[ "${{ github.event.before }}" == "" ]]; then
              #First commit on branch - build anyway
              echo "has_changes=true" >> $GITHUB_OUTPUT
              echo "It's the very first commit on branch, hence proceeding with Docker build.."
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "flask_app/" && echo "has_changes=true" >> $GITHUB_OUTPUT || echo "No changes detected in flask_app/"
          fi
      
      - name: Skip build message
        if: ${{ !steps.check_changes.outputs.has_changes }}
        run: |
          echo "Since no changes in flask_app directory, skipping Docker build and push"

      - name: Set up Docker Buildx
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to DockerHub
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Release Tag
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          RELEASE_TAG="${BRANCH_NAME}-${GITHUB_SHA::6}-$(date +'%Y%m%d')"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          echo "json={\"date\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" >> $GITHUB_OUTPUT

      # - name: Set lowercase image name
      #   run: |
      #     REPO_NAME_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
      #     echo "IMAGE_NAME=${REPO_NAME_LOWERCASE}" >> $GITHUB_ENV

      - name: Build and push Docker image
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.RELEASE_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.vars.outputs.json).date }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ steps.vars.outputs.RELEASE_TAG }}

      # Temporary fix for cache: https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # deploy:
  #   name: Deploy to Environment
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   if: github.event_name != 'pull_request'
  #   environment:
  #     name: ${{ github.event.inputs.environment || 'staging' }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}

  #     - name: Install DVC
  #       run: |
  #         pip install dvc dvc[s3]

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Pull DVC data
  #       run: |
  #         dvc pull -r ${{ env.DVC_REMOTE_NAME }}

  #     - name: Deploy to environment
  #       run: |
  #         echo "Deploying to ${{ github.event.inputs.environment || 'staging' }}"
  #         # Add your deployment scripts or commands here
  #         # For example, using kubectl to deploy to Kubernetes
  #         # kubectl apply -f k8s/${{ github.event.inputs.environment || 'staging' }}/deployment.yaml